; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

	TITLE	C:\Users\Florian\Desktop\IAFinal\ProjetIAFinal\Projet\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
