; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25507.1 

	TITLE	D:\UQAC\IAR\ProjetV2\ProjetIAFinal\Projet\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
