; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

	TITLE	D:\8IAR125 - Intelligence artificielle pour le jeu vidéo\ProjetFinal\Projet\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
